training_data = [

# GREETINGS
("hi", "Hello 👋 | Hi there 😊 | Hey! Ready to manage your finances?"),
("hello", "Hello 😊 How can I help you today?"),
("hey", "Hey 👋 Need help with budgeting or expenses?"),
("good morning", "Good morning ☀️ Ready to manage your finances today?"),
("good evening", "Good evening 😊 Let's review your spending today."),
("how are you", "I am doing great 😊 Ready to help with your finances."),
("what is your name", "My name is FinBuddy AI 🤖💰"),
("who are you", "I am FinBuddy AI, your personal finance assistant."),
("what can you do", "I can track expenses, manage budgets, and give financial advice."),
("thank you", "You are welcome 😊"),
("thanks", "Happy to help 💰"),
("bye", "Goodbye 👋 Spend wisely!"),
("good night", "Good night 🌙 Save smartly."),
("nice to meet you", "Nice to meet you too 😊"),
("can you help me", "Of course 😊 Tell me your financial problem or goal."),
("are you ai", "Yes 🤖 I am an AI-powered personal finance chatbot."),
("do you learn", "Yes 🧠 I learn from admin training."),
("can you remember", "Yes 😊 I remember learned knowledge and financial details."),
("what is your purpose", "My purpose is to help users manage money wisely."),
("do you know me", "I know the financial details you share with me."),

# BUDGET
("what is budget", "A budget is a financial plan for managing income and expenses."),
("why is budgeting important", "Budgeting helps control spending and improve financial stability."),
("how to create budget", "List income, expenses, savings goals, and spending limits."),
("how to control budget", "Track expenses and reduce unnecessary spending."),
("what is monthly budget", "A monthly budget is your planned monthly spending."),
("what is yearly budget", "A yearly budget is a financial plan for one year."),
("how much should i budget", "Budget according to your income and essential expenses."),
("budget advice", "Follow your spending limits and review expenses regularly."),
("how to stick to budget", "Track daily expenses and avoid impulse buying."),
("what is budget planning", "Budget planning means organizing income and expenses."),
("budget tips", "Prioritize needs before wants."),
("how to reduce budget problems", "Track overspending categories and reduce waste."),
("how to improve budget", "Review your spending habits monthly."),
("how to balance budget", "Spend less than your income and save consistently."),
("why do budgets fail", "Budgets fail when spending is not tracked."),
("best budgeting method", "The 50/30/20 rule is a popular budgeting method."),
("what is 50 30 20 rule", "50% needs, 30% wants, 20% savings."),
("what is zero based budget", "Every rupee is assigned a purpose."),
("what is flexible budget", "A flexible budget adjusts according to income changes."),
("how to budget salary", "Divide salary into needs, savings, and future goals."),

# SAVINGS
("what is saving", "Saving means keeping money aside for future needs."),
("why should i save money", "Savings protect you during emergencies."),
("how to save money", "Reduce unnecessary spending and save regularly."),
("how much should i save", "Try saving at least 10% to 20% of income."),
("saving tips", "Save first, spend later."),
("best saving habit", "Track expenses and avoid wasteful spending."),
("what is emergency fund", "An emergency fund is money saved for unexpected situations."),
("how much emergency fund should i have", "Save 3 to 6 months of essential expenses."),
("how to build savings", "Save a small amount consistently every month."),
("i cannot save money", "Start small and reduce unnecessary expenses."),
("saving challenge", "Try saving a fixed amount every week."),
("saving strategy", "Automate savings and avoid impulse purchases."),
("how to increase savings", "Reduce expenses and increase income."),
("how to save salary", "Save before spending."),
("how to save for future", "Create long-term savings goals."),
("how to save for marriage", "Set a separate savings goal and track progress."),
("how to save for education", "Start saving early and avoid unnecessary debt."),
("how to save for travel", "Create a travel budget and save monthly."),
("how to save fast", "Reduce luxury spending temporarily."),
("how to save with low salary", "Focus on essential expenses first."),

# EXPENSES
("what is expense", "An expense is money spent on needs or wants."),
("how to reduce expenses", "Reduce non-essential spending."),
("what is overspending", "Overspending means spending beyond your financial limit."),
("what is smart spending", "Smart spending means buying only necessary items."),
("food expense advice", "Cook at home more often to reduce food costs."),
("transport expense advice", "Use public transport and plan routes."),
("shopping expense advice", "Avoid impulse buying."),
("bill expense advice", "Reduce electricity and subscription costs."),
("rent expense advice", "Manage flexible expenses carefully."),
("i spend too much", "Track expenses daily and reduce unnecessary purchases."),
("how to track expenses", "Record every expense regularly."),
("why are my expenses high", "High expenses may come from overspending or poor budgeting."),
("how to lower monthly expenses", "Reduce unnecessary spending categories."),
("expense management tips", "Track and categorize expenses."),
("what are fixed expenses", "Fixed expenses stay similar every month."),
("what are variable expenses", "Variable expenses change monthly."),
("daily expense advice", "Track daily spending carefully."),
("weekend spending advice", "Set limits for entertainment spending."),
("how to avoid wasteful spending", "Think before buying unnecessary items."),
("how to spend wisely", "Prioritize needs before wants."),

# SALARY & INCOME
("what is salary", "Salary is fixed income from employment."),
("what is income", "Income is money earned from work or investments."),
("how to manage salary", "Divide salary into needs, wants, savings, and investments."),
("salary management tips", "Save before spending."),
("how to increase income", "Improve skills or start side income."),
("low salary advice", "Prioritize essential expenses and avoid debt."),
("high salary advice", "Increase savings and investments."),
("how to use salary wisely", "Plan spending and avoid unnecessary luxury."),
("how to manage monthly income", "Track expenses and savings goals."),
("how to improve financial condition", "Control expenses and increase savings."),
("best use of salary", "Spend wisely and save consistently."),
("salary planning advice", "Create a monthly budget."),
("how to survive with low income", "Focus on essentials and avoid debt."),
("income management", "Track income sources and spending."),
("what is passive income", "Passive income is earned with minimal daily effort."),

# DEBT & LOAN
("what is debt", "Debt is borrowed money that must be repaid."),
("what is loan", "A loan is borrowed money with repayment terms."),
("what is emi", "EMI means Equated Monthly Installment."),
("how to reduce debt", "Pay high-interest debt first."),
("should i take loan", "Take loans only when necessary."),
("loan advice", "Borrow only what you can repay."),
("credit card advice", "Pay bills on time and avoid overspending."),
("what is good debt", "Good debt helps build future value."),
("what is bad debt", "Bad debt is borrowing for unnecessary luxury."),
("how to avoid debt", "Spend within your income."),
("how to pay loan faster", "Pay extra whenever possible."),
("loan repayment tips", "Prioritize high-interest loans."),
("debt stress advice", "Create a repayment plan and reduce unnecessary spending."),
("student loan advice", "Borrow only for important educational needs."),
("car loan advice", "Keep EMI below 20% of salary."),
("home loan advice", "Plan carefully before taking long-term loans."),
("credit card debt help", "Pay more than the minimum amount."),
("loan vs savings", "Use savings wisely before taking unnecessary loans."),
("interest rate meaning", "Interest rate is the cost of borrowing money."),
("how to improve credit score", "Pay bills and loans on time."),

# INVESTMENT
("what is investment", "Investment means using money to earn future profit."),
("what is inflation", "Inflation is the increase in prices over time."),
("what is interest", "Interest is the cost of borrowing or reward for saving."),
("what is compound interest", "Compound interest earns interest on previous interest."),
("how to invest money", "Start investing after building emergency savings."),
("beginner investment advice", "Start with low-risk investments."),
("what is risk", "Risk is the possibility of losing money."),
("what is diversification", "Diversification spreads investments to reduce risk."),
("investment tips", "Research before investing."),
("safe investment advice", "Low-risk investments provide more stability."),
("long term investment advice", "Invest consistently and patiently."),
("short term investment advice", "Short-term investments may have lower returns."),
("what is stock market", "The stock market is where shares are traded."),
("what is mutual fund", "Mutual funds pool money from many investors."),
("what is cryptocurrency", "Cryptocurrency is digital currency."),
("crypto investment advice", "Invest carefully because crypto is risky."),
("gold investment advice", "Gold can be useful for long-term savings."),
("land investment advice", "Research location and legal documents carefully."),
("business investment advice", "Understand risks before investing."),
("retirement investment advice", "Start investing early for retirement."),

# GOALS & BUYING
("i need iphone", "Check salary, savings, and expenses before buying an iPhone."),
("should i buy iphone", "Buy an iPhone only if savings are stable."),
("can i afford iphone", "Affordability depends on salary and savings."),
("i need bike", "Save monthly before buying a bike."),
("should i buy bike", "Check EMI and maintenance costs."),
("can i afford bike", "A bike is affordable if expenses are balanced."),
("i need bicycle", "A bicycle is a low-cost smart purchase."),
("should i buy bicycle", "A bicycle can reduce transport costs."),
("i need car", "Plan fuel, insurance, and EMI carefully."),
("should i buy car", "Keep car EMI below 20% of salary."),
("can i afford car", "Check if monthly costs fit your budget."),
("i need laptop", "Buy a laptop only if necessary for work or study."),
("should i buy laptop", "Choose a laptop based on actual needs."),
("can i afford laptop", "A laptop is affordable if savings remain stable."),
("i need house", "Start a separate house savings fund."),
("should i buy house", "Plan carefully before taking home loans."),
("can i afford house", "Check down payment and EMI affordability."),
("i need land", "Research location and save for down payment."),
("should i buy land", "Land can be a good long-term investment."),
("i need gold", "Buy gold gradually using savings."),

# EMOTIONAL SUPPORT
("i am stressed about money", "Don’t worry 😊 Start with a simple budget."),
("i am worried about debt", "Pay high-interest debt first."),
("motivate me to save money", "Small savings today create financial freedom tomorrow."),
("i failed financially", "Financial mistakes are learning opportunities."),
("i feel poor", "Your situation can improve with discipline and planning."),
("i have money problems", "Track expenses and reduce unnecessary costs."),
("i feel hopeless", "Start small and improve step by step."),
("i need financial advice", "Tell me your financial issue or goal."),
("how to avoid financial stress", "Follow a budget and build emergency savings."),
("i am afraid of loans", "Borrow carefully and plan repayments wisely."),

# AI / VIVA
("what is nlp", "NLP means Natural Language Processing."),
("what is inference engine", "An inference engine maps user input to suitable actions."),
("what is knowledge base", "A knowledge base stores learned information."),
("what ai features do you have", "I use NLP, self-learning, and financial analysis."),
("how do you give personalized advice", "I use salary, savings, expenses, and goals."),
("why are you intelligent", "I use machine learning and inference logic."),
("what is self learning ai", "Self-learning AI improves using learned knowledge."),
("what is chatbot", "A chatbot is software that communicates with users."),
("what is machine learning", "Machine learning helps systems learn from data."),
("what is artificial intelligence", "AI enables computers to perform intelligent tasks."),

# FAMILY FINANCE
("how to manage family expenses", "Track household spending and prioritize essential needs."),
("family budget tips", "Create a monthly family budget and review expenses together."),
("how to save money for family", "Reduce unnecessary spending and build emergency savings."),
("children education savings", "Start education savings early and save consistently."),
("family financial planning", "Plan income, expenses, savings, insurance, and future goals."),
("how to reduce family expenses", "Track wasteful spending and avoid unnecessary luxury purchases."),
("how to support parents financially", "Plan a separate support budget without harming savings."),
("how to save for children", "Create a separate savings account for children’s future."),
("family emergency fund", "Keep emergency savings for medical or unexpected situations."),
("best family budgeting advice", "Spend wisely and save before unnecessary shopping."),

# STUDENT FINANCE
("student budget advice", "Track expenses carefully and avoid unnecessary spending."),
("how to save money as student", "Reduce entertainment expenses and save small amounts regularly."),
("student expense management", "Separate study needs from luxury spending."),
("how to manage pocket money", "Plan spending weekly and avoid impulse purchases."),
("best financial advice for students", "Learn budgeting and saving habits early."),
("how to avoid student debt", "Borrow only for important educational needs."),
("student saving tips", "Save part of pocket money every month."),
("cheap student lifestyle advice", "Focus on needs instead of expensive wants."),
("how to buy laptop for studies", "Choose affordable laptops based on actual academic needs."),
("education financial planning", "Plan tuition, books, and living expenses carefully."),

# BUSINESS FINANCE
("what is business finance", "Business finance manages money for business operations and growth."),
("small business budgeting", "Track revenue and expenses carefully."),
("how to grow business financially", "Control costs and reinvest profits wisely."),
("business saving advice", "Separate personal and business finances."),
("business expense management", "Monitor operational costs regularly."),
("startup financial advice", "Start with realistic budgeting and avoid unnecessary spending."),
("how to invest in business", "Research risks and market demand carefully."),
("business loan advice", "Borrow only if repayment is manageable."),
("business profit advice", "Increase efficiency and reduce wasteful costs."),
("business financial planning", "Set clear goals and track cash flow."),

# RETIREMENT
("what is retirement planning", "Retirement planning prepares financially for life after work."),
("how to save for retirement", "Start saving early and invest consistently."),
("best retirement advice", "Save regularly and avoid unnecessary debt."),
("retirement investment tips", "Long-term investments help retirement growth."),
("how much should i save for retirement", "Save consistently according to future lifestyle needs."),
("retirement budgeting", "Plan future living expenses carefully."),
("why retirement savings important", "Retirement savings provide future financial security."),
("retirement financial freedom", "Early planning improves retirement stability."),
("retirement goal planning", "Set long-term financial targets."),
("safe retirement investments", "Choose low-risk long-term investment options."),

# BANKING
("what is bank account", "A bank account stores and manages money securely."),
("what is savings account", "A savings account helps store money safely."),
("what is current account", "A current account is mainly used for business transactions."),
("how to use bank wisely", "Track transactions and avoid unnecessary fees."),
("online banking safety", "Protect passwords and avoid suspicious links."),
("what is atm", "ATM allows cash withdrawal and banking services."),
("mobile banking advice", "Use secure passwords and official banking apps."),
("bank loan meaning", "A bank loan is borrowed money from a financial institution."),
("bank interest meaning", "Bank interest is money earned or paid on deposits or loans."),
("best banking advice", "Choose reliable banks and manage transactions carefully."),

# INSURANCE
("what is insurance", "Insurance protects against financial loss."),
("why insurance important", "Insurance helps during emergencies and accidents."),
("health insurance advice", "Health insurance reduces medical financial risk."),
("life insurance advice", "Life insurance protects family financial stability."),
("vehicle insurance advice", "Vehicle insurance helps cover accident costs."),
("travel insurance advice", "Travel insurance protects during unexpected travel problems."),
("insurance saving advice", "Choose affordable plans with useful coverage."),
("insurance financial planning", "Insurance should be part of long-term planning."),
("best insurance advice", "Compare policies carefully before buying."),
("what is premium", "Premium is the amount paid for insurance coverage."),

# DAILY LIFE FINANCE
("how to save electricity bill", "Turn off unused devices and use energy-efficient appliances."),
("how to save water bill", "Reduce unnecessary water usage."),
("how to reduce internet bill", "Choose affordable plans and remove unused subscriptions."),
("daily money saving tips", "Track small expenses because they grow over time."),
("shopping budget advice", "Set spending limits before shopping."),
("festival spending advice", "Plan festival budgets carefully and avoid overspending."),
("holiday spending advice", "Save for holidays in advance."),
("food budgeting tips", "Plan meals and avoid food waste."),
("transport saving tips", "Use public transport and reduce unnecessary trips."),
("weekend spending tips", "Set entertainment limits and avoid impulse purchases."),

# TECHNOLOGY PURCHASES
("should i buy gaming laptop", "Buy a gaming laptop only if it matches your real needs and budget."),
("should i buy expensive phone", "Expensive phones should not affect emergency savings."),
("how to buy affordable laptop", "Compare prices and focus on essential features."),
("phone upgrade advice", "Upgrade phones only when truly necessary."),
("best financial decision before buying gadgets", "Check savings and avoid unnecessary debt."),
("how to avoid gadget overspending", "Avoid buying devices only for trends."),
("technology spending advice", "Prioritize useful technology purchases."),
("how to save for gadgets", "Create a separate gadget savings goal."),
("buy now or save first", "Saving first is usually financially safer."),
("luxury purchase advice", "Avoid luxury purchases when savings are low."),

# ADVANCED FINANCE
("what is net worth", "Net worth equals assets minus liabilities."),
("what is asset", "An asset is something valuable you own."),
("what is liability", "A liability is money you owe."),
("what is cash flow", "Cash flow is money moving in and out."),
("positive cash flow meaning", "Positive cash flow means income exceeds expenses."),
("negative cash flow meaning", "Negative cash flow means expenses exceed income."),
("what is financial risk", "Financial risk is the chance of losing money."),
("what is diversification", "Diversification spreads investments to reduce risk."),
("how to build wealth", "Wealth grows through saving, investing, and discipline."),
("how to become millionaire", "Consistent investing and financial discipline build wealth over time."),

# MENTAL & MOTIVATIONAL
("motivate me financially", "Every small financial improvement matters 💰"),
("i feel broke", "Start with budgeting and small savings goals."),
("i want better future", "Consistent saving and smart planning improve the future."),
("i need motivation", "Financial discipline today creates freedom tomorrow."),
("i lost money", "Learn from mistakes and improve your financial planning."),
("i feel stressed", "Take one step at a time and focus on essentials."),
("i cannot control spending", "Track every expense and avoid impulse buying."),
("how to stay financially disciplined", "Follow a budget and avoid emotional spending."),
("i feel insecure financially", "Emergency savings and budgeting improve security."),
("how to stay positive financially", "Focus on gradual improvement and long-term goals."),

# CHATBOT / AI EXTRA
("how do chatbots work", "Chatbots use NLP and decision logic to understand users."),
("what is tfidf", "TF-IDF helps identify important words in text."),
("what is logistic regression", "Logistic regression predicts categories from input data."),
("what is machine learning model", "A machine learning model learns patterns from data."),
("how does your brain work", "I use NLP, inference logic, and a knowledge base."),
("what is intent classification", "Intent classification identifies the purpose of user input."),
("what is self learning", "Self-learning means improving using learned knowledge."),
("what is recommendation system", "A recommendation system gives personalized suggestions."),
("what is database", "A database stores information permanently."),
("what is sqlite", "SQLite is a lightweight database used in applications."),

# CONVERSATION FLOW / FOLLOW-UP REPLIES

("yes i need help", "Sure 😊 Tell me what you want help with: expense, budget, saving, debt, or buying goal."),
("i need your help", "Of course 😊 I can help with budgeting, savings, expenses, debt, or purchase planning."),
("help me", "Sure 😊 Start by telling me your salary, expenses, savings, or financial goal."),
("guide me", "I can guide you step by step. First tell me what you want to do: save money, reduce expenses, or buy something."),
("start", "Great 😊 You can start by typing: my salary is 120000, I spent 500 on food, or set budget 50000."),
("what should i do first", "Start by entering your salary, then your monthly expenses and savings. After that I can give better advice."),
("how to start", "Start with your income and expenses. Example: my salary is 120000 and food expense 30000."),
("what next", "Next, you can add expenses, set a budget, check monthly summary, or ask for saving advice."),
("next", "You can continue by adding expenses, checking budget, or asking finance questions."),
("then", "Next, you can type monthly summary to analyze your spending."),
("okay what next", "Now tell me your salary, savings, or expenses so I can give personalized advice."),
("ok what next", "You can add an expense, set your budget, or tell me your financial goal."),
("fine what next", "Great 😊 Next, tell me your monthly salary or expenses."),
("continue", "Sure 😊 Continue by telling me your expenses, savings, or financial goal."),
("go on", "Sure. Tell me more about your financial situation."),
("tell me more", "I can explain budgeting, saving, debt, investment, or buying decisions. What would you like?"),

# USER CONFUSION
("i do not understand", "No worries 😊 I can explain simply. Tell me which part is confusing: budget, saving, expense, or loan."),
("i dont understand", "That’s okay 😊 I can guide you step by step."),
("i am confused", "No problem 😊 Start by telling me your salary and main expenses."),
("explain simply", "Sure 😊 I will explain in simple words."),
("can you explain", "Yes 😊 Tell me what topic you want me to explain."),
("explain again", "Sure 😊 I can explain again in a simpler way."),
("say in simple way", "Of course 😊 I will explain in a simple and clear way."),
("what do you mean", "I mean you should check income, expenses, savings, and goals before making financial decisions."),
("i dont know", "That’s okay 😊 I can help you step by step."),
("i don't know", "That’s okay 😊 Let’s start with your salary and expenses."),

# ASKING FOR OPTIONS
("what are my options", "Your options are: reduce expenses, increase savings, set a budget, avoid debt, or plan your goal slowly."),
("give me options", "You can choose: expense tracking, budget planning, saving advice, debt help, or buying advice."),
("what can i ask", "You can ask about expenses, budget, savings, debt, loans, investments, or buying goals."),
("what questions can i ask", "You can ask: how to save money, can I afford a bike, monthly summary, or how to reduce debt."),
("show examples", "Examples: I spent 500 on food, set budget 50000, monthly summary, can I afford iPhone."),
("give examples", "Try asking: how to save money, what is budget, I need bike, or how to reduce expenses."),
("example please", "Example: my salary is 120000, my savings 10000, food expense 30000, i need iphone."),
("what should i type", "You can type: my salary is 120000, I spent 500 on food, set budget 50000, or monthly summary."),

# AFTER SALARY
("i entered my salary", "Great 😊 Now enter your monthly expenses like food expense 30000 or transport expense 20000."),
("salary added", "Good 😊 Now tell me your monthly expenses and savings."),
("my salary is saved", "Great. Now add expenses so I can analyze your spending."),
("what after salary", "After salary, enter expenses and savings. Example: food expense 30000, my savings 10000."),
("i told my salary", "Thank you 😊 Now tell me your expenses and savings for better advice."),

# AFTER EXPENSE
("i entered expense", "Great 😊 You can add more expenses or type monthly summary."),
("expense added", "Good 😊 Add more expenses or ask me to analyze spending."),
("what after expense", "After adding expenses, type monthly summary or analyze my spending."),
("i added food expense", "Good. You can add transport, rent, bills, or savings next."),
("i added transport expense", "Good. Add other expenses like food, rent, bills, or savings."),
("i added rent", "Good. Rent is a fixed expense. Now add food, transport, bills, or savings."),
("i added bills", "Good. Now you can ask for monthly summary or saving advice."),

# AFTER SAVINGS
("i entered savings", "Great 😊 Now I can give better personalized advice for your goals."),
("savings added", "Good 😊 Tell me your financial goal, such as iPhone, bike, car, laptop, or house."),
("what after savings", "Now tell me what you want to buy or improve financially."),
("i told my savings", "Great. Now ask me: can I afford iPhone, bike, car, laptop, or house."),

# AFTER BUDGET
("i set budget", "Great 😊 I will compare your spending with your budget."),
("budget added", "Good 😊 Add expenses and ask for monthly summary."),
("what after budget", "After setting budget, add your expenses and ask me to analyze spending."),
("budget is saved", "Great. Now track expenses so I can warn you about overspending."),

# ASK FOR SUMMARY
("show my summary", "Type monthly summary to view your spending report."),
("i want summary", "Sure 😊 Type monthly summary and I will calculate your expenses."),
("how to see summary", "Type monthly summary to see total spending and highest category."),
("show report", "Type monthly summary or open the dashboard to view your report."),
("show dashboard", "You can use the dashboard to see charts, expenses, budget, and recent records."),
("show my expenses", "You can type monthly summary to view your expense breakdown."),
("analyze my money", "Sure 😊 I can analyze your spending after you add expenses."),

# BUYING GOAL FLOW
("i want to buy something", "Tell me what you want to buy: iPhone, bike, bicycle, car, laptop, house, land, or gold."),
("i want to buy a product", "Tell me the product name and your salary/savings so I can advise."),
("i need something expensive", "Before buying expensive items, check salary, expenses, savings, and emergency fund."),
("can i buy this", "Tell me the item name and your salary/savings so I can check affordability."),
("is it worth buying", "It is worth buying only if it supports your needs and does not harm your savings."),
("should i wait or buy", "If savings are low, wait and save first. If budget is stable, you may plan to buy."),
("buy now or later", "If it is not urgent, save first and buy later without debt."),
("help me buy something", "Sure 😊 Tell me what you want to buy and your monthly savings."),
("plan my purchase", "I can help. Tell me the item, estimated price, salary, expenses, and savings."),
("purchase advice", "Buy only if essential expenses, emergency fund, and monthly savings are safe."),

# DEBT CONVERSATION FLOW
("i have debt", "Don’t worry. List your debts, pay high-interest debt first, and avoid new loans."),
("i have loan", "Check your EMI, interest rate, and monthly budget before taking more debt."),
("i cannot pay loan", "Contact your lender, reduce non-essential spending, and create a repayment plan."),
("my emi is high", "If EMI is high, reduce other expenses and avoid taking new loans."),
("debt is stressful", "Debt can be stressful. Start with a clear repayment plan and small consistent payments."),
("how to start paying debt", "Start by listing all debts and paying the highest interest one first."),
("which debt first", "Usually pay high-interest debt first because it grows faster."),
("should i borrow money", "Borrow only if necessary and if repayment is affordable."),
("loan or save", "If it is not urgent, saving first is safer than taking a loan."),
("credit card problem", "Stop new card spending and pay more than the minimum amount monthly."),

# SAVING CONVERSATION FLOW
("i want to save", "Great 😊 Set a monthly savings goal and reduce unnecessary expenses."),
("help me save", "Sure 😊 Tell me your salary and expenses so I can suggest a savings plan."),
("how do i start saving", "Start by saving a small fixed amount every month before spending."),
("i cannot save enough", "Reduce flexible expenses like shopping, entertainment, and restaurant food."),
("i want more savings", "Increase savings by reducing wants and tracking every expense."),
("how to save faster", "Cut non-essential spending temporarily and set a clear savings target."),
("saving plan please", "Tell me your salary, expenses, and goal so I can suggest a saving plan."),
("make saving plan", "Start with 10% of income, then gradually increase to 20% if possible."),
("is my saving enough", "Your saving is enough only if it protects emergencies and supports your goals."),
("how to protect savings", "Keep savings separate from daily spending money."),

# USER REACTIONS
("nice", "Glad you like it 😊 What would you like to do next?"),
("good", "Great 😊 Let’s continue improving your finances."),
("great", "Awesome 😊 Tell me your next financial question."),
("super", "Thank you 😊 I’m ready to help more."),
("perfect", "Great 😊 Continue by asking about expenses, savings, budget, or goals."),
("wow", "Happy to help 😊 Finance becomes easier with planning."),
("not good", "No problem. Tell me what went wrong and I will try to help."),
("wrong answer", "Sorry about that. Admin can teach me the correct answer using teach: question => answer."),
("that is wrong", "Thanks for telling me. Admin can update my knowledge using the teach command."),
("i need better answer", "Sure. Please give more details like salary, expenses, savings, and goal."),

# CLOSING CONVERSATION
("see you", "See you again 😊 Keep saving smartly."),
("talk later", "Sure 😊 I’ll be here when you need finance help."),
("goodbye", "Goodbye 👋 Take care of your finances."),
("finish", "Okay 😊 Remember to track expenses and save regularly."),
("done", "Great 😊 Let me know if you need more financial advice."),
("that is all", "Okay 😊 Happy to help with your financial journey."),
("no thanks", "No problem 😊 Come back anytime for finance advice."),
]